// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

import static org.junit.Assert.assertTrue;

public class ChangeLanguageTest {
	private WebDriver[] drivers = new WebDriver[2];
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@Before
	public void setUp() {
		WebDriverManager.chromedriver().setup();
		WebDriverManager.firefoxdriver().setup();
		drivers[0] = new FirefoxDriver();
		drivers[1] = new ChromeDriver();
		vars = new HashMap<String, Object>();
	}
	
	@Test
	public void changeLanguage() {
		for (WebDriver driver : drivers) {
			driver.get("https://www.ucoz.ru/");
			driver.manage().window().setSize(new Dimension(805, 816));
			driver.findElement(By.id("llink")).click();
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("English"))).click();
            WebElement el = wait.until(ExpectedConditions.elementToBeClickable((By.xpath("//span[contains(text(), 'English')]"))));
            assertTrue("Язык не изменился", el.isDisplayed());
            try{Thread.sleep(2000);}catch(InterruptedException e){e.printStackTrace();}
			driver.quit();
		}
	}
}
