// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreatePaymentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void createPayment() {
    driver.get("https://www.ucoz.ru/");
    driver.manage().window().setSize(new Dimension(1550, 830));
    driver.findElement(By.linkText("Войти")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".nowrap > span")).click();
    vars.put("win8348", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8348").toString());
    driver.findElement(By.cssSelector(".popup-close-btn")).click();
    driver.findElement(By.linkText("Улучшить тариф")).click();
    driver.findElement(By.cssSelector(".tab-switcher-item:nth-child(2) > .tab-switcher-btn")).click();
    driver.findElement(By.cssSelector(".rates-table-rate-button:nth-child(5) > .rates-table-button")).click();
    driver.findElement(By.cssSelector(".upay-icon-iomoney")).click();
    driver.findElement(By.cssSelector(".u-button:nth-child(14)")).click();
  }
}
