// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateNewDomenTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  WebDriverWait wait;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    wait = new WebDriverWait(driver, Duration.ofSeconds(15));
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void createNewDomen() {
    driver.get("https://www.ucoz.ru/");
    driver.manage().window().setSize(new Dimension(1550, 830));
    driver.findElement(By.linkText("Войти")).click();
    driver.findElement(By.id("fEmail")).click();
    driver.findElement(By.id("fEmail")).sendKeys("kostikbushmelev@yandex.ru");
    driver.findElement(By.id("fPassword")).click();
    driver.findElement(By.id("fPassword")).sendKeys("strongpassword");
    driver.findElement(By.id("submit_btn")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".nowrap > span")).click();
    vars.put("win2180", waitForWindow(10000));
    driver.switchTo().window(vars.get("win2180").toString());
    driver.findElement(By.cssSelector(".popup-close-btn")).click();
    driver.findElement(By.linkText("Купить домен")).click();
    driver.findElement(By.cssSelector(".js-zones-list > .u-ios-checkbox_wrapper:nth-child(2) .u-ios-checkbox_body")).click();
    driver.findElement(By.cssSelector(".u-ios-checkbox_wrapper:nth-child(12) .u-ios-checkbox_body")).click();
    driver.findElement(By.cssSelector(".check-domains-button")).click();
  }
}
