// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;

public class LoginTest {
  private WebDriver[] drivers = new WebDriver[2];

  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    WebDriverManager.firefoxdriver().setup();
    drivers[0] = new FirefoxDriver();
    drivers[1] = new ChromeDriver();
  }

  @Test
  public void loginTest() {
    for (WebDriver driver : drivers) {
      driver.get("https://www.ucoz.ru/");
      driver.manage().window().setSize(new Dimension(1550, 830));
      driver.findElement(By.linkText("Войти")).click();
      driver.findElement(By.id("fEmail")).click();
      driver.findElement(By.id("fEmail")).sendKeys("kostikbushmelev@yandex.ru");
      driver.findElement(By.id("fPassword")).click();
      driver.findElement(By.id("fPassword")).sendKeys("strongpassword");
      driver.findElement(By.id("submit_btn")).click();
      driver.quit();
    }
  }
}
